In [2]:
from pathlib import Path
import json
import numpy as np
import pandas as pd

DATA_DIR = Path("data")

def find_file(stem_or_name):
    """
    Finds a file inside DATA_DIR even if extension is missing in the name.
    Example: find_file("build_info") can find build_info.json.
    """
    direct = DATA_DIR / stem_or_name
    if direct.exists():
        return direct
    
    matches = list(DATA_DIR.glob(stem_or_name + ".*"))
    if matches:
        return matches[0]
    
    raise FileNotFoundError(f"Could not find {stem_or_name} in {DATA_DIR.resolve()}")

print("Data folder:", DATA_DIR.resolve())
print("Top-level files/folders:")
for p in DATA_DIR.iterdir():
    print("-", p.name)

Data folder: /workspaces/Project/data
Top-level files/folders:
- original_dataset_windows.xlsx
- rawdata
- build_info.json
- data_final
- scene_index_10s.csv
- split_index.csv
- stats.npz

In [3]:
build_info_path = find_file("build_info")

print("File:", build_info_path)

with open(build_info_path, "r", encoding="utf-8") as f:
    build_info = json.load(f)

build_info

File: data/build_info.json

{'dataset_root': 'C:\\Users\\BILAB\\Desktop\\User_data\\Traj\\agentformer_nusense\\processed_10s_cleaned_data_20260428_5hz',
 'target_hz': 5.0,
 'obs_seconds': 2.0,
 'future_seconds': 5.0,
 'workbook': 'C:\\Users\\BILAB\\Desktop\\User_data\\Traj\\agentformer_nusense\\original_dataset_windows.xlsx',
 'limit_scenes': None,
 'split_counts': {'train': 11626, 'val': 1148, 'test': 1131}}

In [4]:
windows_path = find_file("original_dataset_windows")

print("File:", windows_path)

if windows_path.suffix.lower() in [".xlsx", ".xls"]:
    original_dataset_windows = pd.read_excel(windows_path)
elif windows_path.suffix.lower() == ".csv":
    original_dataset_windows = pd.read_csv(windows_path)
else:
    raise ValueError(f"Unsupported file type: {windows_path.suffix}")

print(original_dataset_windows.shape)
original_dataset_windows.head()

File: data/original_dataset_windows.xlsx
(594, 11)

,participant,scenario,wz,original_start_unix,original_end_unix,original_duration_s,original_start_s,original_end_s,chosen_start_s,chosen_end_s,note
0,P10,S1_normal,1,1.765554e+09,1.765554e+09,10.0,0,10.0,NaN,NaN,NaN
1,P10,S1_normal,2,1.765554e+09,1.765554e+09,10.0,0,10.0,NaN,NaN,NaN
2,P10,S1_normal,3,1.765554e+09,1.765554e+09,10.0,0,10.0,NaN,NaN,NaN
3,P10,S2_noWarning,1,1.765553e+09,1.765553e+09,17.0,0,17.0,5.0,18.0,NaN
4,P10,S2_noWarning,2,1.765553e+09,1.765553e+09,10.5,0,10.5,NaN,NaN,NaN

In [5]:
for col in original_dataset_windows.columns:
    print("\n" + "="*80)
    print("Column:", col)
    print("Number of unique values:", original_dataset_windows[col].nunique(dropna=False))
    print(original_dataset_windows[col].unique())

================================================================================
Column: participant
Number of unique values: 33
<StringArray>
['P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20',
 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29',  'P2', 'P30',
 'P31', 'P32', 'P33', 'P34',  'P3',  'P4',  'P5',  'P6',  'P7',  'P8',  'P9']
Length: 33, dtype: str

================================================================================
Column: scenario
Number of unique values: 6
<StringArray>
['S1_normal', 'S2_noWarning', 'S3_rainy', 'S4_curve', 'S5_nighttime',
 'S6_truck']
Length: 6, dtype: str

================================================================================
Column: wz
Number of unique values: 3
[1 2 3]

================================================================================
Column: original_start_unix
Number of unique values: 594
[1.76555366e+09 1.76555368e+09 1.76555370e+09 1.76555307e+09
 1.76555312e+09 1.76555315e+09 1.76555410e+09 1.76555423e+09
 1.76555426e+09 1.76555450e+09 1.76555453e+09 1.76555458e+09
 1.76555492e+09 1.76555494e+09 1.76555497e+09 1.76555528e+09
 1.76555532e+09 1.76555537e+09 1.76556069e+09 1.76556071e+09
 1.76556073e+09 1.76556032e+09 1.76556036e+09 1.76556039e+09
 1.76556114e+09 1.76556118e+09 1.76556122e+09 1.76555984e+09
 1.76555986e+09 1.76555991e+09 1.76556160e+09 1.76556163e+09
 1.76556165e+09 1.76556200e+09 1.76556203e+09 1.76556205e+09
 1.76581655e+09 1.76581657e+09 1.76581659e+09 1.76581611e+09
 1.76581615e+09 1.76581618e+09 1.76581702e+09 1.76581705e+09
 1.76581709e+09 1.76581557e+09 1.76581558e+09 1.76581561e+09
 1.76581751e+09 1.76581753e+09 1.76581755e+09 1.76581787e+09
 1.76581790e+09 1.76581792e+09 1.76582524e+09 1.76582526e+09
 1.76582528e+09 1.76582484e+09 1.76582487e+09 1.76582489e+09
 1.76582576e+09 1.76582579e+09 1.76582583e+09 1.76582440e+09
 1.76582442e+09 1.76582446e+09 1.76582636e+09 1.76582638e+09
 1.76582641e+09 1.76582673e+09 1.76582677e+09 1.76582678e+09
 1.76590994e+09 1.76590995e+09 1.76590997e+09 1.76590960e+09
 1.76590962e+09 1.76590965e+09 1.76591029e+09 1.76591031e+09
 1.76591034e+09 1.76590918e+09 1.76590921e+09 1.76590922e+09
 1.76591067e+09 1.76591070e+09 1.76591071e+09 1.76591101e+09
 1.76591102e+09 1.76591104e+09 1.76591697e+09 1.76591699e+09
 1.76591701e+09 1.76591660e+09 1.76591662e+09 1.76591665e+09
 1.76591739e+09 1.76591742e+09 1.76591748e+09 1.76591617e+09
 1.76591620e+09 1.76591625e+09 1.76591788e+09 1.76591791e+09
 1.76591793e+09 1.76591829e+09 1.76591832e+09 1.76591834e+09
 1.76592361e+09 1.76592365e+09 1.76592368e+09 1.76592400e+09
 1.76592402e+09 1.76592404e+09 1.76592434e+09 1.76592437e+09
 1.76592442e+09 1.76592319e+09 1.76592320e+09 1.76592324e+09
 1.76592478e+09 1.76592480e+09 1.76592481e+09 1.76592286e+09
 1.76592290e+09 1.76592292e+09 1.76600029e+09 1.76600031e+09
 1.76600033e+09 1.76600068e+09 1.76600070e+09 1.76600072e+09
 1.76600115e+09 1.76600118e+09 1.76600122e+09 1.76599993e+09
 1.76599994e+09 1.76599996e+09 1.76600154e+09 1.76600157e+09
 1.76600159e+09 1.76599959e+09 1.76599961e+09 1.76599964e+09
 1.77152604e+09 1.77152605e+09 1.77152607e+09 1.77152633e+09
 1.77152634e+09 1.77152636e+09 1.77152668e+09 1.77152672e+09
 1.77152676e+09 1.77152570e+09 1.77152571e+09 1.77152574e+09
 1.77152714e+09 1.77152717e+09 1.77152718e+09 1.77152539e+09
 1.77152543e+09 1.77152544e+09 1.77161224e+09 1.77161226e+09
 1.77161227e+09 1.77161263e+09 1.77161266e+09 1.77161269e+09
 1.77161301e+09 1.77161305e+09 1.77161309e+09 1.77161182e+09
 1.77161184e+09 1.77161188e+09 1.77161342e+09 1.77161345e+09
 1.77161347e+09 1.77161127e+09 1.77161130e+09 1.77161134e+09
 1.77161941e+09 1.77161944e+09 1.77161945e+09 1.77161976e+09
 1.77161979e+09 1.77161983e+09 1.77162012e+09 1.77162014e+09
 1.77162019e+09 1.77161914e+09 1.77161915e+09 1.77161916e+09
 1.77162051e+09 1.77162053e+09 1.77162055e+09 1.77161883e+09
 1.77161886e+09 1.77161887e+09 1.77205127e+09 1.77205132e+09
 1.77205134e+09 1.77205178e+09 1.77205181e+09 1.77205185e+09
 1.77205227e+09 1.77205231e+09 1.77205235e+09 1.77205278e+09
 1.77205281e+09 1.77205285e+09 1.77205321e+09 1.77205323e+09
 1.77205325e+09 1.77205354e+09 1.77205359e+09 1.77205362e+09
 1.77205806e+09 1.77205810e+09 1.77205814e+09 1.77205856e+09
 1.77205862e+09 1.77205869e+09 1.77205913e+09 1.77205917e+09
 1.77205925e+09 1.77205967e+09 1.77205970e+09 1.77205978e+09
 1.77206023e+09 1.77206027e+09 1.77206031e+09 1.77206067e+09
 1.77206071e+09 1.77206073e+09 1.77212313e+09 1.77212315e+09
 1.77212317e+09 1.77212374e+09 1.77212376e+09 1.77212378e+09
 1.77212418e+09 1.77212422e+09 1.77212427e+09 1.77212460e+09
 1.77212463e+09 1.77212467e+09 1.77212501e+09 1.77212503e+09
 1.77212507e+09 1.77212540e+09 1.77212543e+09 1.77212547e+09
 1.77213080e+09 1.77213084e+09 1.77213086e+09 1.77213121e+09
 1.77213124e+09 1.77213126e+09 1.77213160e+09 1.77213164e+09
 1.77213168e+09 1.77213214e+09 1.77213217e+09 1.77213220e+09
 1.77213249e+09 1.77213251e+09 1.77213253e+09 1.77213287e+09
 1.77213291e+09 1.77213295e+09 1.77220958e+09 1.77220960e+09
 1.77220962e+09 1.77220998e+09 1.77221002e+09 1.77221006e+09
 1.77221040e+09 1.77221043e+09 1.77221047e+09 1.77221083e+09
 1.77221085e+09 1.77221088e+09 1.77221129e+09 1.77221132e+09
 1.77221134e+09 1.77221167e+09 1.77221172e+09 1.77221174e+09
 1.77222431e+09 1.77222434e+09 1.77222435e+09 1.77222394e+09
 1.77222396e+09 1.77222399e+09 1.77222476e+09 1.77222479e+09
 1.77222483e+09 1.77222559e+09 1.77222560e+09 1.77222563e+09
 1.77222600e+09 1.77222602e+09 1.77222604e+09 1.77222522e+09
 1.77222525e+09 1.77222528e+09 1.77249301e+09 1.77249303e+09
 1.77249305e+09 1.77249265e+09 1.77249270e+09 1.77249273e+09
 1.77249339e+09 1.77249343e+09 1.77249350e+09 1.77249438e+09
 1.77249439e+09 1.77249442e+09 1.77249478e+09 1.77249481e+09
 1.77249483e+09 1.77249397e+09 1.77249400e+09 1.77249405e+09
 1.77255689e+09 1.77255691e+09 1.77255693e+09 1.77255652e+09
 1.77255658e+09 1.77255660e+09 1.77255727e+09 1.77255731e+09
 1.77255735e+09 1.77255803e+09 1.77255807e+09 1.77255812e+09
 1.77255843e+09 1.77255846e+09 1.77255848e+09 1.77255768e+09
 1.77255772e+09 1.77255776e+09 1.77256107e+09 1.77256110e+09
 1.77256112e+09 1.77256057e+09 1.77256064e+09 1.77256068e+09
 1.77256147e+09 1.77256152e+09 1.77256159e+09 1.77256238e+09
 1.77256242e+09 1.77256246e+09 1.77256281e+09 1.77256284e+09
 1.77256286e+09 1.77256191e+09 1.77256195e+09 1.77256199e+09
 1.76410518e+09 1.76410520e+09 1.76410522e+09 1.76410566e+09
 1.76410570e+09 1.76410575e+09 1.76410612e+09 1.76410616e+09
 1.76410621e+09 1.76410663e+09 1.76410665e+09 1.76410667e+09
 1.76410712e+09 1.76410715e+09 1.76410717e+09 1.76410758e+09
 1.76410763e+09 1.76410766e+09 1.77265895e+09 1.77265899e+09
 1.77265902e+09 1.77265851e+09 1.77265855e+09 1.77265859e+09
 1.77265938e+09 1.77265941e+09 1.77265947e+09 1.77266127e+09
 1.77266129e+09 1.77266131e+09 1.77266162e+09 1.77266165e+09
 1.77266167e+09 1.77266089e+09 1.77266092e+09 1.77266095e+09
 1.77273649e+09 1.77273652e+09 1.77273656e+09 1.77273610e+09
 1.77273613e+09 1.77273615e+09 1.77273694e+09 1.77273698e+09
 1.77273702e+09 1.77273568e+09 1.77273571e+09 1.77273575e+09
 1.77273517e+09 1.77273520e+09 1.77273522e+09 1.77273734e+09
 1.77273738e+09 1.77273742e+09 1.77325087e+09 1.77325089e+09
 1.77325091e+09 1.77325047e+09 1.77325050e+09 1.77325055e+09
 1.77325125e+09 1.77325128e+09 1.77325132e+09 1.77325005e+09
 1.77325006e+09 1.77325009e+09 1.77324969e+09 1.77324972e+09
 1.77324973e+09 1.77325167e+09 1.77325171e+09 1.77325175e+09
 1.77333024e+09 1.77333026e+09 1.77333028e+09 1.77332988e+09
 1.77332992e+09 1.77332994e+09 1.77333065e+09 1.77333068e+09
 1.77333072e+09 1.77332948e+09 1.77332949e+09 1.77332952e+09
 1.77332898e+09 1.77332901e+09 1.77332903e+09 1.77333110e+09
 1.77333114e+09 1.77333118e+09 1.77341661e+09 1.77341663e+09
 1.77341665e+09 1.77341626e+09 1.77341629e+09 1.77341631e+09
 1.77341697e+09 1.77341700e+09 1.77341704e+09 1.77341583e+09
 1.77341585e+09 1.77341589e+09 1.77341547e+09 1.77341549e+09
 1.77341551e+09 1.77341736e+09 1.77341740e+09 1.77341744e+09
 1.76486183e+09 1.76486185e+09 1.76486187e+09 1.76486239e+09
 1.76486243e+09 1.76486246e+09 1.76486296e+09 1.76486316e+09
 1.76486309e+09 1.76486349e+09 1.76486352e+09 1.76486365e+09
 1.76486405e+09 1.76486407e+09 1.76486409e+09 1.76486447e+09
 1.76486449e+09 1.76486451e+09 1.76530814e+09 1.76530816e+09
 1.76530818e+09 1.76530557e+09 1.76530561e+09 1.76530565e+09
 1.76530622e+09 1.76530630e+09 1.76530635e+09 1.76530680e+09
 1.76530683e+09 1.76530687e+09 1.76530724e+09 1.76530727e+09
 1.76530729e+09 1.76530772e+09 1.76530776e+09 1.76530780e+09
 1.76531471e+09 1.76531474e+09 1.76531480e+09 1.76531523e+09
 1.76531527e+09 1.76531531e+09 1.76531568e+09 1.76531572e+09
 1.76531577e+09 1.76531616e+09 1.76531618e+09 1.76531623e+09
 1.76531680e+09 1.76531683e+09 1.76531687e+09 1.76531726e+09
 1.76531731e+09 1.76531734e+09 1.76539049e+09 1.76539051e+09
 1.76539053e+09 1.76539011e+09 1.76539014e+09 1.76539017e+09
 1.76539112e+09 1.76539121e+09 1.76539125e+09 1.76539174e+09
 1.76539177e+09 1.76539190e+09 1.76539240e+09 1.76539242e+09
 1.76539244e+09 1.76539281e+09 1.76539284e+09 1.76539289e+09
 1.76539439e+09 1.76539444e+09 1.76539446e+09 1.76539393e+09
 1.76539397e+09 1.76539400e+09 1.76539489e+09 1.76539500e+09
 1.76539503e+09 1.76539535e+09 1.76539536e+09 1.76539547e+09
 1.76539579e+09 1.76539580e+09 1.76539582e+09 1.76539623e+09
 1.76539625e+09 1.76539627e+09 1.76548269e+09 1.76548271e+09
 1.76548273e+09 1.76548235e+09 1.76548239e+09 1.76548243e+09
 1.76548303e+09 1.76548306e+09 1.76548308e+09 1.76548340e+09
 1.76548341e+09 1.76548344e+09 1.76548380e+09 1.76548383e+09
 1.76548384e+09 1.76548418e+09 1.76548422e+09 1.76548423e+09
 1.76548802e+09 1.76548804e+09 1.76548806e+09 1.76548757e+09
 1.76548760e+09 1.76548763e+09 1.76548843e+09 1.76548845e+09
 1.76548849e+09 1.76548895e+09 1.76548896e+09 1.76548899e+09
 1.76548936e+09 1.76548939e+09 1.76548941e+09 1.76548975e+09
 1.76548978e+09 1.76548980e+09]

================================================================================
Column: original_end_unix
Number of unique values: 594
[1.76555367e+09 1.76555369e+09 1.76555371e+09 1.76555309e+09
 1.76555313e+09 1.76555316e+09 1.76555411e+09 1.76555424e+09
 1.76555427e+09 1.76555451e+09 1.76555454e+09 1.76555459e+09
 1.76555493e+09 1.76555496e+09 1.76555499e+09 1.76555529e+09
 1.76555533e+09 1.76555538e+09 1.76556070e+09 1.76556072e+09
 1.76556074e+09 1.76556033e+09 1.76556037e+09 1.76556040e+09
 1.76556114e+09 1.76556118e+09 1.76556123e+09 1.76555985e+09
 1.76555988e+09 1.76555992e+09 1.76556161e+09 1.76556164e+09
 1.76556167e+09 1.76556201e+09 1.76556204e+09 1.76556206e+09
 1.76581656e+09 1.76581658e+09 1.76581660e+09 1.76581612e+09
 1.76581616e+09 1.76581619e+09 1.76581703e+09 1.76581706e+09
 1.76581710e+09 1.76581558e+09 1.76581559e+09 1.76581562e+09
 1.76581752e+09 1.76581754e+09 1.76581757e+09 1.76581788e+09
 1.76581791e+09 1.76581793e+09 1.76582525e+09 1.76582527e+09
 1.76582530e+09 1.76582485e+09 1.76582488e+09 1.76582490e+09
 1.76582577e+09 1.76582580e+09 1.76582584e+09 1.76582441e+09
 1.76582444e+09 1.76582448e+09 1.76582637e+09 1.76582639e+09
 1.76582642e+09 1.76582674e+09 1.76582678e+09 1.76582679e+09
 1.76590995e+09 1.76590996e+09 1.76590998e+09 1.76590961e+09
 1.76590963e+09 1.76590966e+09 1.76591030e+09 1.76591032e+09
 1.76591035e+09 1.76590919e+09 1.76590922e+09 1.76590923e+09
 1.76591068e+09 1.76591071e+09 1.76591072e+09 1.76591102e+09
 1.76591103e+09 1.76591105e+09 1.76591698e+09 1.76591700e+09
 1.76591702e+09 1.76591661e+09 1.76591663e+09 1.76591666e+09
 1.76591740e+09 1.76591743e+09 1.76591749e+09 1.76591619e+09
 1.76591621e+09 1.76591626e+09 1.76591789e+09 1.76591792e+09
 1.76591795e+09 1.76591830e+09 1.76591833e+09 1.76591836e+09
 1.76592362e+09 1.76592366e+09 1.76592369e+09 1.76592401e+09
 1.76592403e+09 1.76592405e+09 1.76592435e+09 1.76592438e+09
 1.76592443e+09 1.76592320e+09 1.76592321e+09 1.76592325e+09
 1.76592479e+09 1.76592481e+09 1.76592482e+09 1.76592287e+09
 1.76592291e+09 1.76592294e+09 1.76600030e+09 1.76600032e+09
 1.76600034e+09 1.76600069e+09 1.76600071e+09 1.76600073e+09
 1.76600117e+09 1.76600119e+09 1.76600123e+09 1.76599994e+09
 1.76599995e+09 1.76599997e+09 1.76600155e+09 1.76600158e+09
 1.76600160e+09 1.76599960e+09 1.76599962e+09 1.76599965e+09
 1.77152605e+09 1.77152606e+09 1.77152608e+09 1.77152634e+09
 1.77152635e+09 1.77152637e+09 1.77152669e+09 1.77152673e+09
 1.77152677e+09 1.77152571e+09 1.77152572e+09 1.77152575e+09
 1.77152715e+09 1.77152718e+09 1.77152721e+09 1.77152540e+09
 1.77152544e+09 1.77152545e+09 1.77161225e+09 1.77161227e+09
 1.77161229e+09 1.77161264e+09 1.77161267e+09 1.77161270e+09
 1.77161302e+09 1.77161306e+09 1.77161310e+09 1.77161183e+09
 1.77161186e+09 1.77161190e+09 1.77161343e+09 1.77161346e+09
 1.77161349e+09 1.77161128e+09 1.77161131e+09 1.77161136e+09
 1.77161942e+09 1.77161945e+09 1.77161946e+09 1.77161977e+09
 1.77161980e+09 1.77161984e+09 1.77162013e+09 1.77162015e+09
 1.77162020e+09 1.77161915e+09 1.77161916e+09 1.77161917e+09
 1.77162052e+09 1.77162055e+09 1.77162058e+09 1.77161884e+09
 1.77161887e+09 1.77161888e+09 1.77205128e+09 1.77205133e+09
 1.77205135e+09 1.77205179e+09 1.77205182e+09 1.77205187e+09
 1.77205228e+09 1.77205232e+09 1.77205236e+09 1.77205279e+09
 1.77205282e+09 1.77205286e+09 1.77205322e+09 1.77205324e+09
 1.77205327e+09 1.77205355e+09 1.77205360e+09 1.77205363e+09
 1.77205808e+09 1.77205812e+09 1.77205816e+09 1.77205858e+09
 1.77205863e+09 1.77205870e+09 1.77205914e+09 1.77205918e+09
 1.77205926e+09 1.77205969e+09 1.77205972e+09 1.77205979e+09
 1.77206024e+09 1.77206029e+09 1.77206033e+09 1.77206069e+09
 1.77206072e+09 1.77206075e+09 1.77212314e+09 1.77212316e+09
 1.77212318e+09 1.77212375e+09 1.77212377e+09 1.77212379e+09
 1.77212419e+09 1.77212423e+09 1.77212429e+09 1.77212461e+09
 1.77212464e+09 1.77212469e+09 1.77212502e+09 1.77212506e+09
 1.77212509e+09 1.77212541e+09 1.77212544e+09 1.77212549e+09
 1.77213081e+09 1.77213085e+09 1.77213088e+09 1.77213122e+09
 1.77213125e+09 1.77213127e+09 1.77213161e+09 1.77213165e+09
 1.77213169e+09 1.77213215e+09 1.77213219e+09 1.77213221e+09
 1.77213250e+09 1.77213252e+09 1.77213256e+09 1.77213288e+09
 1.77213292e+09 1.77213297e+09 1.77220959e+09 1.77220961e+09
 1.77220964e+09 1.77220999e+09 1.77221003e+09 1.77221008e+09
 1.77221041e+09 1.77221044e+09 1.77221049e+09 1.77221085e+09
 1.77221086e+09 1.77221090e+09 1.77221130e+09 1.77221133e+09
 1.77221136e+09 1.77221168e+09 1.77221173e+09 1.77221176e+09
 1.77222433e+09 1.77222435e+09 1.77222436e+09 1.77222395e+09
 1.77222397e+09 1.77222400e+09 1.77222477e+09 1.77222480e+09
 1.77222484e+09 1.77222560e+09 1.77222561e+09 1.77222565e+09
 1.77222601e+09 1.77222603e+09 1.77222606e+09 1.77222523e+09
 1.77222526e+09 1.77222530e+09 1.77249302e+09 1.77249304e+09
 1.77249307e+09 1.77249267e+09 1.77249271e+09 1.77249275e+09
 1.77249340e+09 1.77249344e+09 1.77249352e+09 1.77249439e+09
 1.77249440e+09 1.77249444e+09 1.77249479e+09 1.77249482e+09
 1.77249485e+09 1.77249398e+09 1.77249402e+09 1.77249406e+09
 1.77255690e+09 1.77255692e+09 1.77255694e+09 1.77255653e+09
 1.77255659e+09 1.77255662e+09 1.77255728e+09 1.77255732e+09
 1.77255736e+09 1.77255805e+09 1.77255808e+09 1.77255813e+09
 1.77255844e+09 1.77255847e+09 1.77255850e+09 1.77255769e+09
 1.77255773e+09 1.77255777e+09 1.77256108e+09 1.77256111e+09
 1.77256113e+09 1.77256058e+09 1.77256065e+09 1.77256070e+09
 1.77256148e+09 1.77256153e+09 1.77256161e+09 1.77256239e+09
 1.77256243e+09 1.77256248e+09 1.77256282e+09 1.77256285e+09
 1.77256288e+09 1.77256193e+09 1.77256196e+09 1.77256201e+09
 1.76410519e+09 1.76410521e+09 1.76410523e+09 1.76410567e+09
 1.76410571e+09 1.76410576e+09 1.76410613e+09 1.76410617e+09
 1.76410622e+09 1.76410664e+09 1.76410666e+09 1.76410668e+09
 1.76410713e+09 1.76410716e+09 1.76410719e+09 1.76410759e+09
 1.76410764e+09 1.76410767e+09 1.77265898e+09 1.77265901e+09
 1.77265905e+09 1.77265853e+09 1.77265856e+09 1.77265861e+09
 1.77265939e+09 1.77265943e+09 1.77265949e+09 1.77266128e+09
 1.77266130e+09 1.77266133e+09 1.77266163e+09 1.77266166e+09
 1.77266169e+09 1.77266090e+09 1.77266093e+09 1.77266097e+09
 1.77273651e+09 1.77273653e+09 1.77273657e+09 1.77273611e+09
 1.77273614e+09 1.77273617e+09 1.77273695e+09 1.77273699e+09
 1.77273704e+09 1.77273569e+09 1.77273572e+09 1.77273576e+09
 1.77273518e+09 1.77273521e+09 1.77273524e+09 1.77273735e+09
 1.77273739e+09 1.77273743e+09 1.77325088e+09 1.77325090e+09
 1.77325092e+09 1.77325048e+09 1.77325052e+09 1.77325057e+09
 1.77325126e+09 1.77325129e+09 1.77325134e+09 1.77325006e+09
 1.77325007e+09 1.77325011e+09 1.77324970e+09 1.77324973e+09
 1.77324974e+09 1.77325168e+09 1.77325172e+09 1.77325177e+09
 1.77333025e+09 1.77333027e+09 1.77333029e+09 1.77332989e+09
 1.77332993e+09 1.77332996e+09 1.77333066e+09 1.77333069e+09
 1.77333074e+09 1.77332949e+09 1.77332950e+09 1.77332954e+09
 1.77332899e+09 1.77332902e+09 1.77332905e+09 1.77333111e+09
 1.77333115e+09 1.77333119e+09 1.77341662e+09 1.77341664e+09
 1.77341666e+09 1.77341627e+09 1.77341630e+09 1.77341633e+09
 1.77341698e+09 1.77341701e+09 1.77341706e+09 1.77341584e+09
 1.77341586e+09 1.77341591e+09 1.77341548e+09 1.77341551e+09
 1.77341554e+09 1.77341737e+09 1.77341741e+09 1.77341745e+09
 1.76486184e+09 1.76486186e+09 1.76486188e+09 1.76486241e+09
 1.76486244e+09 1.76486247e+09 1.76486297e+09 1.76486317e+09
 1.76486310e+09 1.76486350e+09 1.76486353e+09 1.76486366e+09
 1.76486406e+09 1.76486408e+09 1.76486411e+09 1.76486448e+09
 1.76486450e+09 1.76486452e+09 1.76530815e+09 1.76530817e+09
 1.76530819e+09 1.76530558e+09 1.76530563e+09 1.76530566e+09
 1.76530623e+09 1.76530631e+09 1.76530636e+09 1.76530681e+09
 1.76530684e+09 1.76530689e+09 1.76530725e+09 1.76530728e+09
 1.76530731e+09 1.76530773e+09 1.76530777e+09 1.76530781e+09
 1.76531472e+09 1.76531476e+09 1.76531481e+09 1.76531524e+09
 1.76531528e+09 1.76531532e+09 1.76531569e+09 1.76531573e+09
 1.76531578e+09 1.76531618e+09 1.76531619e+09 1.76531624e+09
 1.76531681e+09 1.76531684e+09 1.76531688e+09 1.76531728e+09
 1.76531732e+09 1.76531735e+09 1.76539050e+09 1.76539052e+09
 1.76539054e+09 1.76539013e+09 1.76539015e+09 1.76539018e+09
 1.76539113e+09 1.76539122e+09 1.76539125e+09 1.76539175e+09
 1.76539178e+09 1.76539191e+09 1.76539241e+09 1.76539243e+09
 1.76539245e+09 1.76539282e+09 1.76539285e+09 1.76539290e+09
 1.76539440e+09 1.76539445e+09 1.76539447e+09 1.76539394e+09
 1.76539398e+09 1.76539401e+09 1.76539490e+09 1.76539501e+09
 1.76539504e+09 1.76539536e+09 1.76539537e+09 1.76539548e+09
 1.76539580e+09 1.76539582e+09 1.76539583e+09 1.76539624e+09
 1.76539626e+09 1.76539628e+09 1.76548270e+09 1.76548272e+09
 1.76548274e+09 1.76548236e+09 1.76548240e+09 1.76548244e+09
 1.76548304e+09 1.76548307e+09 1.76548309e+09 1.76548341e+09
 1.76548342e+09 1.76548345e+09 1.76548381e+09 1.76548384e+09
 1.76548385e+09 1.76548419e+09 1.76548423e+09 1.76548424e+09
 1.76548803e+09 1.76548805e+09 1.76548807e+09 1.76548758e+09
 1.76548762e+09 1.76548765e+09 1.76548844e+09 1.76548847e+09
 1.76548851e+09 1.76548896e+09 1.76548897e+09 1.76548900e+09
 1.76548937e+09 1.76548940e+09 1.76548943e+09 1.76548977e+09
 1.76548979e+09 1.76548981e+09]

================================================================================
Column: original_duration_s
Number of unique values: 40
[10.  17.  10.5  9.5 19.5 13.5 14.   9.  12.  11.5 15.5 12.5  8.5 19.
  8.  11.  28.5 18.  13.  15.  14.5 24.5 16.5 26.   7.5 22.  16.  21.
 25.  23.5 17.5 29.  21.5 23.  18.5 22.5 20.5  6.   7.   6.5]

================================================================================
Column: original_start_s
Number of unique values: 1
[0]

================================================================================
Column: original_end_s
Number of unique values: 40
[10.  17.  10.5  9.5 19.5 13.5 14.   9.  12.  11.5 15.5 12.5  8.5 19.
  8.  11.  28.5 18.  13.  15.  14.5 24.5 16.5 26.   7.5 22.  16.  21.
 25.  23.5 17.5 29.  21.5 23.  18.5 22.5 20.5  6.   7.   6.5]


In [6]:
scene_index_path = DATA_DIR / "scene_index_10s.csv"

scene_index_10s = pd.read_csv(scene_index_path)

print(scene_index_10s.shape)
scene_index_10s.head()

(594, 16)

,participant,scenario,wz,n_frames,has_ego,has_worker,t_start_unix,t_end_unix,txt_path,rich_path,target_hz,source_original_start_unix,source_original_end_unix,chosen_start_s,chosen_end_s,note
0,P10,S1_normal,1,51,1,1,1.765554e+09,1.765554e+09,NaN,_rich\P10_S1_normal_WZ1.csv,5.0,1.765554e+09,1.765554e+09,NaN,NaN,NaN
1,P10,S1_normal,2,51,1,1,1.765554e+09,1.765554e+09,NaN,_rich\P10_S1_normal_WZ2.csv,5.0,1.765554e+09,1.765554e+09,NaN,NaN,NaN
2,P10,S1_normal,3,51,1,1,1.765554e+09,1.765554e+09,NaN,_rich\P10_S1_normal_WZ3.csv,5.0,1.765554e+09,1.765554e+09,NaN,NaN,NaN
3,P10,S2_noWarning,1,66,1,1,1.765553e+09,1.765553e+09,NaN,_rich\P10_S2_noWarning_WZ1.csv,5.0,1.765553e+09,1.765553e+09,5.0,18.0,NaN
4,P10,S2_noWarning,2,53,1,1,1.765553e+09,1.765553e+09,NaN,_rich\P10_S2_noWarning_WZ2.csv,5.0,1.765553e+09,1.765553e+09,NaN,NaN,NaN

In [7]:
for col in scene_index_10s.columns:
    print("\n" + "="*80)
    print("Column:", col)
    print("Number of unique values:", scene_index_10s[col].nunique(dropna=False))
    print(scene_index_10s[col].unique())

================================================================================
Column: participant
Number of unique values: 33
<StringArray>
['P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20',
 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29',  'P2', 'P30',
 'P31', 'P32', 'P33', 'P34',  'P3',  'P4',  'P5',  'P6',  'P7',  'P8',  'P9']
Length: 33, dtype: str

================================================================================
Column: scenario
Number of unique values: 6
<StringArray>
['S1_normal', 'S2_noWarning', 'S3_rainy', 'S4_curve', 'S5_nighttime',
 'S6_truck']
Length: 6, dtype: str

================================================================================
Column: wz
Number of unique values: 3
[1 2 3]

================================================================================
Column: n_frames
Number of unique values: 37
[ 51  66  53  48  46  98  68  71  61  78  36  41  56  43  58  63  86  33
  38  96 143  76  73 101  83 116  81 106 111 108 131  88 113  91 118  31
 103]

================================================================================
Column: has_ego
Number of unique values: 1
[1]

================================================================================
Column: has_worker
Number of unique values: 1
[1]

================================================================================
Column: t_start_unix
Number of unique values: 594
[1.76555366e+09 1.76555368e+09 1.76555370e+09 1.76555308e+09
 1.76555312e+09 1.76555315e+09 1.76555410e+09 1.76555423e+09
 1.76555426e+09 1.76555450e+09 1.76555453e+09 1.76555458e+09
 1.76555493e+09 1.76555494e+09 1.76555497e+09 1.76555529e+09
 1.76555532e+09 1.76555537e+09 1.76556069e+09 1.76556071e+09
 1.76556073e+09 1.76556032e+09 1.76556036e+09 1.76556039e+09
 1.76556114e+09 1.76556118e+09 1.76556122e+09 1.76555984e+09
 1.76555986e+09 1.76555991e+09 1.76556160e+09 1.76556163e+09
 1.76556165e+09 1.76556200e+09 1.76556203e+09 1.76556205e+09
 1.76581655e+09 1.76581657e+09 1.76581659e+09 1.76581611e+09
 1.76581615e+09 1.76581619e+09 1.76581703e+09 1.76581705e+09
 1.76581709e+09 1.76581557e+09 1.76581558e+09 1.76581561e+09
 1.76581751e+09 1.76581753e+09 1.76581755e+09 1.76581787e+09
 1.76581790e+09 1.76581792e+09 1.76582524e+09 1.76582526e+09
 1.76582528e+09 1.76582485e+09 1.76582487e+09 1.76582490e+09
 1.76582576e+09 1.76582579e+09 1.76582583e+09 1.76582440e+09
 1.76582442e+09 1.76582446e+09 1.76582636e+09 1.76582638e+09
 1.76582641e+09 1.76582673e+09 1.76582677e+09 1.76582679e+09
 1.76590994e+09 1.76590995e+09 1.76590997e+09 1.76590960e+09
 1.76590962e+09 1.76590965e+09 1.76591029e+09 1.76591031e+09
 1.76591034e+09 1.76590918e+09 1.76590921e+09 1.76590922e+09
 1.76591068e+09 1.76591070e+09 1.76591071e+09 1.76591101e+09
 1.76591103e+09 1.76591104e+09 1.76591697e+09 1.76591699e+09
 1.76591701e+09 1.76591660e+09 1.76591662e+09 1.76591666e+09
 1.76591739e+09 1.76591742e+09 1.76591748e+09 1.76591617e+09
 1.76591620e+09 1.76591625e+09 1.76591789e+09 1.76591791e+09
 1.76591793e+09 1.76591829e+09 1.76591832e+09 1.76591835e+09
 1.76592361e+09 1.76592365e+09 1.76592368e+09 1.76592400e+09
 1.76592402e+09 1.76592405e+09 1.76592434e+09 1.76592437e+09
 1.76592442e+09 1.76592319e+09 1.76592320e+09 1.76592324e+09
 1.76592478e+09 1.76592480e+09 1.76592481e+09 1.76592287e+09
 1.76592290e+09 1.76592293e+09 1.76600029e+09 1.76600031e+09
 1.76600033e+09 1.76600068e+09 1.76600070e+09 1.76600073e+09
 1.76600116e+09 1.76600118e+09 1.76600122e+09 1.76599993e+09
 1.76599994e+09 1.76599996e+09 1.76600155e+09 1.76600157e+09
 1.76600159e+09 1.76599959e+09 1.76599961e+09 1.76599964e+09
 1.77152604e+09 1.77152605e+09 1.77152607e+09 1.77152633e+09
 1.77152634e+09 1.77152636e+09 1.77152669e+09 1.77152672e+09
 1.77152676e+09 1.77152570e+09 1.77152571e+09 1.77152574e+09
 1.77152714e+09 1.77152717e+09 1.77152718e+09 1.77152540e+09
 1.77152543e+09 1.77152544e+09 1.77161224e+09 1.77161226e+09
 1.77161228e+09 1.77161263e+09 1.77161266e+09 1.77161269e+09
 1.77161301e+09 1.77161306e+09 1.77161309e+09 1.77161182e+09
 1.77161184e+09 1.77161188e+09 1.77161342e+09 1.77161345e+09
 1.77161347e+09 1.77161127e+09 1.77161130e+09 1.77161134e+09
 1.77161941e+09 1.77161944e+09 1.77161945e+09 1.77161976e+09
 1.77161979e+09 1.77161983e+09 1.77162012e+09 1.77162014e+09
 1.77162019e+09 1.77161914e+09 1.77161915e+09 1.77161916e+09
 1.77162052e+09 1.77162053e+09 1.77162055e+09 1.77161883e+09
 1.77161886e+09 1.77161887e+09 1.77205127e+09 1.77205132e+09
 1.77205134e+09 1.77205178e+09 1.77205181e+09 1.77205185e+09
 1.77205227e+09 1.77205231e+09 1.77205235e+09 1.77205278e+09
 1.77205281e+09 1.77205285e+09 1.77205321e+09 1.77205323e+09
 1.77205325e+09 1.77205354e+09 1.77205359e+09 1.77205362e+09
 1.77205806e+09 1.77205810e+09 1.77205814e+09 1.77205856e+09
 1.77205862e+09 1.77205869e+09 1.77205913e+09 1.77205917e+09
 1.77205925e+09 1.77205967e+09 1.77205970e+09 1.77205978e+09
 1.77206023e+09 1.77206027e+09 1.77206031e+09 1.77206067e+09
 1.77206071e+09 1.77206073e+09 1.77212313e+09 1.77212315e+09
 1.77212317e+09 1.77212374e+09 1.77212376e+09 1.77212378e+09
 1.77212418e+09 1.77212422e+09 1.77212428e+09 1.77212460e+09
 1.77212463e+09 1.77212468e+09 1.77212501e+09 1.77212504e+09
 1.77212507e+09 1.77212540e+09 1.77212543e+09 1.77212547e+09
 1.77213080e+09 1.77213084e+09 1.77213086e+09 1.77213121e+09
 1.77213124e+09 1.77213126e+09 1.77213160e+09 1.77213164e+09
 1.77213168e+09 1.77213214e+09 1.77213217e+09 1.77213220e+09
 1.77213249e+09 1.77213251e+09 1.77213253e+09 1.77213287e+09
 1.77213291e+09 1.77213295e+09 1.77220958e+09 1.77220960e+09
 1.77220962e+09 1.77220998e+09 1.77221002e+09 1.77221006e+09
 1.77221040e+09 1.77221044e+09 1.77221048e+09 1.77221083e+09
 1.77221085e+09 1.77221088e+09 1.77221129e+09 1.77221132e+09
 1.77221135e+09 1.77221167e+09 1.77221172e+09 1.77221174e+09
 1.77222431e+09 1.77222434e+09 1.77222436e+09 1.77222394e+09
 1.77222396e+09 1.77222399e+09 1.77222476e+09 1.77222479e+09
 1.77222483e+09 1.77222559e+09 1.77222560e+09 1.77222563e+09
 1.77222600e+09 1.77222602e+09 1.77222605e+09 1.77222522e+09
 1.77222525e+09 1.77222528e+09 1.77249302e+09 1.77249303e+09
 1.77249305e+09 1.77249265e+09 1.77249270e+09 1.77249273e+09
 1.77249339e+09 1.77249343e+09 1.77249351e+09 1.77249438e+09
 1.77249439e+09 1.77249442e+09 1.77249478e+09 1.77249481e+09
 1.77249483e+09 1.77249397e+09 1.77249400e+09 1.77249405e+09
 1.77255689e+09 1.77255691e+09 1.77255693e+09 1.77255652e+09
 1.77255658e+09 1.77255660e+09 1.77255727e+09 1.77255731e+09
 1.77255735e+09 1.77255803e+09 1.77255807e+09 1.77255812e+09
 1.77255843e+09 1.77255846e+09 1.77255848e+09 1.77255768e+09
 1.77255772e+09 1.77255776e+09 1.77256107e+09 1.77256110e+09
 1.77256112e+09 1.77256057e+09 1.77256064e+09 1.77256068e+09
 1.77256147e+09 1.77256153e+09 1.77256160e+09 1.77256238e+09
 1.77256242e+09 1.77256246e+09 1.77256281e+09 1.77256284e+09
 1.77256286e+09 1.77256191e+09 1.77256195e+09 1.77256199e+09
 1.76410518e+09 1.76410520e+09 1.76410522e+09 1.76410567e+09
 1.76410570e+09 1.76410575e+09 1.76410612e+09 1.76410616e+09
 1.76410621e+09 1.76410663e+09 1.76410665e+09 1.76410667e+09
 1.76410712e+09 1.76410715e+09 1.76410717e+09 1.76410758e+09
 1.76410763e+09 1.76410766e+09 1.77265896e+09 1.77265899e+09
 1.77265903e+09 1.77265851e+09 1.77265855e+09 1.77265859e+09
 1.77265938e+09 1.77265942e+09 1.77265947e+09 1.77266127e+09
 1.77266129e+09 1.77266131e+09 1.77266162e+09 1.77266165e+09
 1.77266167e+09 1.77266089e+09 1.77266092e+09 1.77266095e+09
 1.77273649e+09 1.77273652e+09 1.77273656e+09 1.77273610e+09
 1.77273613e+09 1.77273615e+09 1.77273694e+09 1.77273698e+09
 1.77273703e+09 1.77273568e+09 1.77273571e+09 1.77273575e+09
 1.77273518e+09 1.77273520e+09 1.77273522e+09 1.77273734e+09
 1.77273738e+09 1.77273742e+09 1.77325087e+09 1.77325089e+09
 1.77325091e+09 1.77325047e+09 1.77325051e+09 1.77325055e+09
 1.77325125e+09 1.77325128e+09 1.77325133e+09 1.77325005e+09
 1.77325006e+09 1.77325009e+09 1.77324969e+09 1.77324972e+09
 1.77324974e+09 1.77325167e+09 1.77325171e+09 1.77325175e+09
 1.77333024e+09 1.77333026e+09 1.77333028e+09 1.77332988e+09
 1.77332992e+09 1.77332994e+09 1.77333065e+09 1.77333068e+09
 1.77333072e+09 1.77332948e+09 1.77332949e+09 1.77332952e+09
 1.77332898e+09 1.77332901e+09 1.77332903e+09 1.77333110e+09
 1.77333114e+09 1.77333118e+09 1.77341661e+09 1.77341663e+09
 1.77341665e+09 1.77341626e+09 1.77341629e+09 1.77341631e+09
 1.77341697e+09 1.77341700e+09 1.77341704e+09 1.77341583e+09
 1.77341585e+09 1.77341589e+09 1.77341547e+09 1.77341549e+09
 1.77341551e+09 1.77341736e+09 1.77341740e+09 1.77341744e+09
 1.76486183e+09 1.76486185e+09 1.76486187e+09 1.76486240e+09
 1.76486243e+09 1.76486246e+09 1.76486296e+09 1.76486316e+09
 1.76486309e+09 1.76486349e+09 1.76486352e+09 1.76486365e+09
 1.76486405e+09 1.76486407e+09 1.76486409e+09 1.76486448e+09
 1.76486449e+09 1.76486451e+09 1.76530814e+09 1.76530816e+09
 1.76530818e+09 1.76530558e+09 1.76530562e+09 1.76530565e+09
 1.76530622e+09 1.76530630e+09 1.76530635e+09 1.76530680e+09
 1.76530683e+09 1.76530687e+09 1.76530725e+09 1.76530727e+09
 1.76530729e+09 1.76530772e+09 1.76530776e+09 1.76530780e+09
 1.76531471e+09 1.76531474e+09 1.76531480e+09 1.76531524e+09
 1.76531527e+09 1.76531531e+09 1.76531568e+09 1.76531572e+09
 1.76531577e+09 1.76531616e+09 1.76531618e+09 1.76531623e+09
 1.76531680e+09 1.76531683e+09 1.76531687e+09 1.76531727e+09
 1.76531731e+09 1.76531734e+09 1.76539049e+09 1.76539051e+09
 1.76539053e+09 1.76539012e+09 1.76539014e+09 1.76539017e+09
 1.76539112e+09 1.76539121e+09 1.76539125e+09 1.76539174e+09
 1.76539177e+09 1.76539190e+09 1.76539240e+09 1.76539242e+09
 1.76539244e+09 1.76539281e+09 1.76539284e+09 1.76539289e+09
 1.76539439e+09 1.76539444e+09 1.76539446e+09 1.76539393e+09
 1.76539397e+09 1.76539401e+09 1.76539489e+09 1.76539500e+09
 1.76539503e+09 1.76539535e+09 1.76539536e+09 1.76539547e+09
 1.76539579e+09 1.76539580e+09 1.76539582e+09 1.76539623e+09
 1.76539625e+09 1.76539627e+09 1.76548269e+09 1.76548271e+09
 1.76548273e+09 1.76548235e+09 1.76548239e+09 1.76548243e+09
 1.76548303e+09 1.76548306e+09 1.76548308e+09 1.76548340e+09
 1.76548341e+09 1.76548344e+09 1.76548380e+09 1.76548383e+09
 1.76548384e+09 1.76548418e+09 1.76548422e+09 1.76548424e+09
 1.76548802e+09 1.76548804e+09 1.76548806e+09 1.76548757e+09
 1.76548760e+09 1.76548764e+09 1.76548843e+09 1.76548846e+09
 1.76548849e+09 1.76548895e+09 1.76548896e+09 1.76548899e+09
 1.76548936e+09 1.76548939e+09 1.76548941e+09 1.76548976e+09
 1.76548978e+09 1.76548980e+09]

================================================================================
Column: t_end_unix
Number of unique values: 594
[1.76555367e+09 1.76555369e+09 1.76555371e+09 1.76555309e+09
 1.76555313e+09 1.76555316e+09 1.76555411e+09 1.76555424e+09
 1.76555427e+09 1.76555451e+09 1.76555454e+09 1.76555459e+09
 1.76555494e+09 1.76555495e+09 1.76555499e+09 1.76555529e+09
 1.76555533e+09 1.76555538e+09 1.76556070e+09 1.76556072e+09
 1.76556074e+09 1.76556033e+09 1.76556037e+09 1.76556040e+09
 1.76556114e+09 1.76556118e+09 1.76556123e+09 1.76555985e+09
 1.76555988e+09 1.76555992e+09 1.76556161e+09 1.76556164e+09
 1.76556167e+09 1.76556201e+09 1.76556204e+09 1.76556206e+09
 1.76581656e+09 1.76581658e+09 1.76581660e+09 1.76581612e+09
 1.76581616e+09 1.76581619e+09 1.76581703e+09 1.76581706e+09
 1.76581710e+09 1.76581558e+09 1.76581559e+09 1.76581562e+09
 1.76581752e+09 1.76581754e+09 1.76581757e+09 1.76581788e+09
 1.76581791e+09 1.76581793e+09 1.76582525e+09 1.76582527e+09
 1.76582530e+09 1.76582486e+09 1.76582488e+09 1.76582491e+09
 1.76582577e+09 1.76582580e+09 1.76582584e+09 1.76582441e+09
 1.76582444e+09 1.76582448e+09 1.76582637e+09 1.76582639e+09
 1.76582642e+09 1.76582674e+09 1.76582678e+09 1.76582680e+09
 1.76590995e+09 1.76590996e+09 1.76590998e+09 1.76590961e+09
 1.76590963e+09 1.76590966e+09 1.76591030e+09 1.76591032e+09
 1.76591035e+09 1.76590919e+09 1.76590922e+09 1.76590923e+09
 1.76591068e+09 1.76591071e+09 1.76591072e+09 1.76591102e+09
 1.76591103e+09 1.76591105e+09 1.76591698e+09 1.76591700e+09
 1.76591702e+09 1.76591661e+09 1.76591663e+09 1.76591667e+09
 1.76591740e+09 1.76591743e+09 1.76591749e+09 1.76591619e+09
 1.76591621e+09 1.76591626e+09 1.76591790e+09 1.76591792e+09
 1.76591795e+09 1.76591830e+09 1.76591833e+09 1.76591836e+09
 1.76592362e+09 1.76592366e+09 1.76592369e+09 1.76592401e+09
 1.76592403e+09 1.76592406e+09 1.76592435e+09 1.76592438e+09
 1.76592443e+09 1.76592320e+09 1.76592321e+09 1.76592325e+09
 1.76592479e+09 1.76592481e+09 1.76592482e+09 1.76592288e+09
 1.76592291e+09 1.76592294e+09 1.76600030e+09 1.76600032e+09
 1.76600034e+09 1.76600069e+09 1.76600071e+09 1.76600073e+09
 1.76600117e+09 1.76600119e+09 1.76600123e+09 1.76599994e+09
 1.76599995e+09 1.76599997e+09 1.76600155e+09 1.76600158e+09
 1.76600160e+09 1.76599960e+09 1.76599962e+09 1.76599965e+09
 1.77152605e+09 1.77152606e+09 1.77152608e+09 1.77152634e+09
 1.77152635e+09 1.77152637e+09 1.77152669e+09 1.77152673e+09
 1.77152677e+09 1.77152571e+09 1.77152572e+09 1.77152575e+09
 1.77152715e+09 1.77152718e+09 1.77152721e+09 1.77152540e+09
 1.77152544e+09 1.77152545e+09 1.77161225e+09 1.77161227e+09
 1.77161229e+09 1.77161264e+09 1.77161267e+09 1.77161270e+09
 1.77161302e+09 1.77161306e+09 1.77161310e+09 1.77161183e+09
 1.77161185e+09 1.77161190e+09 1.77161343e+09 1.77161346e+09
 1.77161349e+09 1.77161128e+09 1.77161131e+09 1.77161136e+09
 1.77161942e+09 1.77161945e+09 1.77161946e+09 1.77161977e+09
 1.77161980e+09 1.77161984e+09 1.77162013e+09 1.77162015e+09
 1.77162020e+09 1.77161915e+09 1.77161916e+09 1.77161917e+09
 1.77162053e+09 1.77162055e+09 1.77162058e+09 1.77161884e+09
 1.77161887e+09 1.77161888e+09 1.77205128e+09 1.77205133e+09
 1.77205135e+09 1.77205179e+09 1.77205182e+09 1.77205187e+09
 1.77205228e+09 1.77205232e+09 1.77205236e+09 1.77205279e+09
 1.77205282e+09 1.77205286e+09 1.77205322e+09 1.77205324e+09
 1.77205327e+09 1.77205355e+09 1.77205360e+09 1.77205363e+09
 1.77205808e+09 1.77205812e+09 1.77205816e+09 1.77205858e+09
 1.77205863e+09 1.77205870e+09 1.77205914e+09 1.77205918e+09
 1.77205926e+09 1.77205969e+09 1.77205972e+09 1.77205979e+09
 1.77206024e+09 1.77206029e+09 1.77206033e+09 1.77206069e+09
 1.77206072e+09 1.77206075e+09 1.77212314e+09 1.77212316e+09
 1.77212318e+09 1.77212375e+09 1.77212377e+09 1.77212379e+09
 1.77212419e+09 1.77212423e+09 1.77212429e+09 1.77212461e+09
 1.77212464e+09 1.77212469e+09 1.77212502e+09 1.77212506e+09
 1.77212509e+09 1.77212541e+09 1.77212544e+09 1.77212549e+09
 1.77213081e+09 1.77213085e+09 1.77213088e+09 1.77213122e+09
 1.77213125e+09 1.77213127e+09 1.77213161e+09 1.77213165e+09
 1.77213169e+09 1.77213215e+09 1.77213219e+09 1.77213221e+09
 1.77213250e+09 1.77213252e+09 1.77213256e+09 1.77213288e+09
 1.77213292e+09 1.77213297e+09 1.77220959e+09 1.77220961e+09
 1.77220964e+09 1.77220999e+09 1.77221003e+09 1.77221008e+09
 1.77221041e+09 1.77221044e+09 1.77221049e+09 1.77221085e+09
 1.77221086e+09 1.77221090e+09 1.77221130e+09 1.77221133e+09
 1.77221136e+09 1.77221168e+09 1.77221173e+09 1.77221176e+09
 1.77222433e+09 1.77222435e+09 1.77222437e+09 1.77222395e+09
 1.77222397e+09 1.77222400e+09 1.77222477e+09 1.77222480e+09
 1.77222484e+09 1.77222560e+09 1.77222561e+09 1.77222565e+09
 1.77222601e+09 1.77222603e+09 1.77222606e+09 1.77222523e+09
 1.77222526e+09 1.77222530e+09 1.77249303e+09 1.77249304e+09
 1.77249306e+09 1.77249267e+09 1.77249271e+09 1.77249275e+09
 1.77249340e+09 1.77249344e+09 1.77249352e+09 1.77249439e+09
 1.77249440e+09 1.77249444e+09 1.77249479e+09 1.77249482e+09
 1.77249485e+09 1.77249398e+09 1.77249402e+09 1.77249406e+09
 1.77255690e+09 1.77255692e+09 1.77255694e+09 1.77255653e+09
 1.77255659e+09 1.77255662e+09 1.77255728e+09 1.77255732e+09
 1.77255736e+09 1.77255805e+09 1.77255808e+09 1.77255813e+09
 1.77255844e+09 1.77255847e+09 1.77255850e+09 1.77255769e+09
 1.77255773e+09 1.77255777e+09 1.77256108e+09 1.77256111e+09
 1.77256113e+09 1.77256058e+09 1.77256065e+09 1.77256070e+09
 1.77256148e+09 1.77256154e+09 1.77256161e+09 1.77256239e+09
 1.77256243e+09 1.77256248e+09 1.77256282e+09 1.77256285e+09
 1.77256288e+09 1.77256193e+09 1.77256196e+09 1.77256201e+09
 1.76410519e+09 1.76410521e+09 1.76410523e+09 1.76410568e+09
 1.76410571e+09 1.76410576e+09 1.76410613e+09 1.76410617e+09
 1.76410622e+09 1.76410664e+09 1.76410666e+09 1.76410668e+09
 1.76410713e+09 1.76410716e+09 1.76410719e+09 1.76410760e+09
 1.76410764e+09 1.76410767e+09 1.77265898e+09 1.77265901e+09
 1.77265905e+09 1.77265853e+09 1.77265856e+09 1.77265861e+09
 1.77265939e+09 1.77265943e+09 1.77265949e+09 1.77266128e+09
 1.77266130e+09 1.77266133e+09 1.77266163e+09 1.77266166e+09
 1.77266169e+09 1.77266090e+09 1.77266093e+09 1.77266097e+09
 1.77273651e+09 1.77273653e+09 1.77273657e+09 1.77273611e+09
 1.77273614e+09 1.77273617e+09 1.77273695e+09 1.77273699e+09
 1.77273704e+09 1.77273569e+09 1.77273572e+09 1.77273576e+09
 1.77273519e+09 1.77273521e+09 1.77273524e+09 1.77273735e+09
 1.77273739e+09 1.77273743e+09 1.77325088e+09 1.77325090e+09
 1.77325092e+09 1.77325048e+09 1.77325052e+09 1.77325057e+09
 1.77325126e+09 1.77325129e+09 1.77325134e+09 1.77325006e+09
 1.77325007e+09 1.77325011e+09 1.77324970e+09 1.77324973e+09
 1.77324975e+09 1.77325168e+09 1.77325172e+09 1.77325177e+09
 1.77333025e+09 1.77333027e+09 1.77333029e+09 1.77332989e+09
 1.77332993e+09 1.77332996e+09 1.77333066e+09 1.77333069e+09
 1.77333073e+09 1.77332949e+09 1.77332950e+09 1.77332954e+09
 1.77332899e+09 1.77332902e+09 1.77332905e+09 1.77333111e+09
 1.77333115e+09 1.77333119e+09 1.77341662e+09 1.77341664e+09
 1.77341666e+09 1.77341627e+09 1.77341630e+09 1.77341633e+09
 1.77341698e+09 1.77341701e+09 1.77341706e+09 1.77341584e+09
 1.77341586e+09 1.77341591e+09 1.77341548e+09 1.77341550e+09
 1.77341554e+09 1.77341737e+09 1.77341741e+09 1.77341745e+09
 1.76486184e+09 1.76486186e+09 1.76486188e+09 1.76486241e+09
 1.76486244e+09 1.76486247e+09 1.76486297e+09 1.76486317e+09
 1.76486310e+09 1.76486350e+09 1.76486353e+09 1.76486366e+09
 1.76486406e+09 1.76486408e+09 1.76486411e+09 1.76486448e+09
 1.76486450e+09 1.76486452e+09 1.76530815e+09 1.76530817e+09
 1.76530819e+09 1.76530558e+09 1.76530563e+09 1.76530567e+09
 1.76530623e+09 1.76530631e+09 1.76530636e+09 1.76530681e+09
 1.76530684e+09 1.76530689e+09 1.76530726e+09 1.76530728e+09
 1.76530731e+09 1.76530774e+09 1.76530777e+09 1.76530781e+09
 1.76531472e+09 1.76531476e+09 1.76531481e+09 1.76531524e+09
 1.76531528e+09 1.76531532e+09 1.76531569e+09 1.76531573e+09
 1.76531578e+09 1.76531618e+09 1.76531619e+09 1.76531624e+09
 1.76531681e+09 1.76531684e+09 1.76531688e+09 1.76531728e+09
 1.76531732e+09 1.76531736e+09 1.76539050e+09 1.76539052e+09
 1.76539054e+09 1.76539013e+09 1.76539015e+09 1.76539018e+09
 1.76539113e+09 1.76539122e+09 1.76539125e+09 1.76539175e+09
 1.76539178e+09 1.76539191e+09 1.76539241e+09 1.76539243e+09
 1.76539245e+09 1.76539282e+09 1.76539285e+09 1.76539290e+09
 1.76539440e+09 1.76539445e+09 1.76539447e+09 1.76539394e+09
 1.76539398e+09 1.76539402e+09 1.76539490e+09 1.76539501e+09
 1.76539504e+09 1.76539536e+09 1.76539537e+09 1.76539548e+09
 1.76539580e+09 1.76539582e+09 1.76539583e+09 1.76539624e+09
 1.76539626e+09 1.76539628e+09 1.76548270e+09 1.76548272e+09
 1.76548274e+09 1.76548236e+09 1.76548240e+09 1.76548244e+09
 1.76548304e+09 1.76548307e+09 1.76548309e+09 1.76548341e+09
 1.76548342e+09 1.76548345e+09 1.76548381e+09 1.76548384e+09
 1.76548385e+09 1.76548419e+09 1.76548422e+09 1.76548425e+09
 1.76548803e+09 1.76548805e+09 1.76548807e+09 1.76548758e+09
 1.76548762e+09 1.76548766e+09 1.76548844e+09 1.76548847e+09
 1.76548851e+09 1.76548896e+09 1.76548897e+09 1.76548900e+09
 1.76548937e+09 1.76548940e+09 1.76548943e+09 1.76548977e+09
 1.76548979e+09 1.76548981e+09]

================================================================================
Column: txt_path
Number of unique values: 1
[nan]

================================================================================
Column: rich_path
Number of unique values: 594
<StringArray>

In [8]:
split_index_path = DATA_DIR / "split_index.csv"

split_index = pd.read_csv(split_index_path)

print(split_index.shape)
split_index.head()

(13905, 14)

,sample,participant,scenario,wz,obs_T,fut_T,t_anchor,t_min,t_max,n_seg_frames,n_gaze_rows,seg_dir,gaze_file,split
0,P10_S1_normal_WZ1_s0000,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0000\seg,aligned\P10_S1_normal_WZ1_s0000\gaze.csv,train
1,P10_S1_normal_WZ1_s0001,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,69,aligned\P10_S1_normal_WZ1_s0001\seg,aligned\P10_S1_normal_WZ1_s0001\gaze.csv,train
2,P10_S1_normal_WZ1_s0002,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0002\seg,aligned\P10_S1_normal_WZ1_s0002\gaze.csv,train
3,P10_S1_normal_WZ1_s0003,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0003\seg,aligned\P10_S1_normal_WZ1_s0003\gaze.csv,train
4,P10_S1_normal_WZ1_s0004,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0004\seg,aligned\P10_S1_normal_WZ1_s0004\gaze.csv,train

In [9]:
for col in split_index.columns:
    print("\n" + "="*80)
    print("Column:", col)
    print("Number of unique values:", split_index[col].nunique(dropna=False))
    print(split_index[col].unique())

================================================================================
Column: sample
Number of unique values: 13905
<StringArray>
['P10_S1_normal_WZ1_s0000', 'P10_S1_normal_WZ1_s0001',
 'P10_S1_normal_WZ1_s0002', 'P10_S1_normal_WZ1_s0003',
 'P10_S1_normal_WZ1_s0004', 'P10_S1_normal_WZ1_s0005',
 'P10_S1_normal_WZ1_s0006', 'P10_S1_normal_WZ1_s0007',
 'P10_S1_normal_WZ1_s0008', 'P10_S1_normal_WZ1_s0009',
 ...
   'P9_S6_truck_WZ3_s0002',   'P9_S6_truck_WZ3_s0003',
   'P9_S6_truck_WZ3_s0004',   'P9_S6_truck_WZ3_s0005',
   'P9_S6_truck_WZ3_s0006',   'P9_S6_truck_WZ3_s0007',
   'P9_S6_truck_WZ3_s0008',   'P9_S6_truck_WZ3_s0009',
   'P9_S6_truck_WZ3_s0010',   'P9_S6_truck_WZ3_s0011']
Length: 13905, dtype: str

================================================================================
Column: participant
Number of unique values: 33
<StringArray>
['P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20',
 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29',  'P2', 'P30',
 'P31', 'P32', 'P33', 'P34',  'P3',  'P4',  'P5',  'P6',  'P7',  'P8',  'P9']
Length: 33, dtype: str

================================================================================
Column: scenario
Number of unique values: 6
<StringArray>
['S1_normal', 'S2_noWarning', 'S3_rainy', 'S4_curve', 'S5_nighttime',
 'S6_truck']
Length: 6, dtype: str

================================================================================
Column: wz
Number of unique values: 3
[1 2 3]

================================================================================
Column: obs_T
Number of unique values: 1
[10]

================================================================================
Column: fut_T
Number of unique values: 1
[25]

================================================================================
Column: t_anchor
Number of unique values: 13905
[1.76555367e+09 1.76555367e+09 1.76555367e+09 ... 1.76548981e+09
 1.76548981e+09 1.76548981e+09]

================================================================================
Column: t_min
Number of unique values: 13905
[1.76555366e+09 1.76555366e+09 1.76555366e+09 ... 1.76548981e+09
 1.76548981e+09 1.76548981e+09]

================================================================================
Column: t_max
Number of unique values: 13905
[1.76555367e+09 1.76555367e+09 1.76555367e+09 ... 1.76548981e+09
 1.76548981e+09 1.76548981e+09]

================================================================================
Column: n_seg_frames
Number of unique values: 23
[68 69 67 66 65 64 63 62 56 57 58 59 60 61 50 49 48 47 55 54 53 52 51]

================================================================================
Column: n_gaze_rows
Number of unique values: 4
[68 69 67  0]

================================================================================
Column: seg_dir
Number of unique values: 13905
<StringArray>
['aligned\P10_S1_normal_WZ1_s0000\seg', 'aligned\P10_S1_normal_WZ1_s0001\seg',
 'aligned\P10_S1_normal_WZ1_s0002\seg', 'aligned\P10_S1_normal_WZ1_s0003\seg',
 'aligned\P10_S1_normal_WZ1_s0004\seg', 'aligned\P10_S1_normal_WZ1_s0005\seg',
 'aligned\P10_S1_normal_WZ1_s0006\seg', 'aligned\P10_S1_normal_WZ1_s0007\seg',
 'aligned\P10_S1_normal_WZ1_s0008\seg', 'aligned\P10_S1_normal_WZ1_s0009\seg',
 ...
   'aligned\P9_S6_truck_WZ3_s0002\seg',   'aligned\P9_S6_truck_WZ3_s0003\seg',
   'aligned\P9_S6_truck_WZ3_s0004\seg',   'aligned\P9_S6_truck_WZ3_s0005\seg',
   'aligned\P9_S6_truck_WZ3_s0006\seg',   'aligned\P9_S6_truck_WZ3_s0007\seg',
   'aligned\P9_S6_truck_WZ3_s0008\seg',   'aligned\P9_S6_truck_WZ3_s0009\seg',
   'aligned\P9_S6_truck_WZ3_s0010\seg',   'aligned\P9_S6_truck_WZ3_s0011\seg']
Length: 13905, dtype: str

================================================================================
Column: gaze_file
Number of unique values: 13905
<StringArray>
['aligned\P10_S1_normal_WZ1_s0000\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0001\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0002\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0003\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0004\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0005\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0006\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0007\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0008\gaze.csv',
 'aligned\P10_S1_normal_WZ1_s0009\gaze.csv',
 ...
   'aligned\P9_S6_truck_WZ3_s0002\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0003\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0004\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0005\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0006\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0007\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0008\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0009\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0010\gaze.csv',
   'aligned\P9_S6_truck_WZ3_s0011\gaze.csv']
Length: 13905, dtype: str

================================================================================
Column: split
Number of unique values: 3
<StringArray>
['train', 'test', 'val']
Length: 3, dtype: str

In [10]:
stats_path = DATA_DIR / "stats.npz"

stats = np.load(stats_path, allow_pickle=True)

print("Keys inside stats.npz:")
print(stats.files)

for key in stats.files:
    arr = stats[key]
    print("\nKey:", key)
    print("Shape:", arr.shape)
    print("Dtype:", arr.dtype)
    print("Preview:")
    print(arr[:5] if arr.ndim > 0 else arr)

Keys inside stats.npz:
['xy_scale', 'v_mean', 'v_std', 'a_mean', 'a_std', 'n_samples', 'eps_attn']

Key: xy_scale
Shape: ()
Dtype: float32
Preview:
50.0

Key: v_mean
Shape: (2,)
Dtype: float32
Preview:
[8.446403   0.35086685]

Key: v_std
Shape: (2,)
Dtype: float32
Preview:
[5.2026234 2.4204705]

Key: a_mean
Shape: (4,)
Dtype: float32
Preview:
[-5.0704203 -5.618188  -6.7843137 -6.5211864]

Key: a_std
Shape: (4,)
Dtype: float32
Preview:
[1.044049  1.2521594 1.7187133 2.2535257]

Key: n_samples
Shape: ()
Dtype: int64
Preview:
11626

Key: eps_attn
Shape: ()
Dtype: float32
Preview:
1e-09

In [11]:
rawdata_dir = DATA_DIR / "rawdata"

print("rawdata exists:", rawdata_dir.exists())
print("Files/folders inside rawdata:")

for p in sorted(rawdata_dir.iterdir())[:30]:
    print("-", p.name, "| folder" if p.is_dir() else "| file")

rawdata exists: True
Files/folders inside rawdata:
- WZ1 | folder
- WZ2 | folder
- WZ3 | folder

In [12]:
data_final_dir = DATA_DIR / "data_final"

print("data_final exists:", data_final_dir.exists())
print("Files/folders inside data_final:")

for p in sorted(data_final_dir.iterdir())[:30]:
    print("-", p.name, "| folder" if p.is_dir() else "| file")

data_final exists: True
Files/folders inside data_final:
- WZ1 | folder
- WZ2 | folder
- WZ3 | folder
- sample_manifest.csv | file

In [13]:
def preview_file(path, n=5):
    print("\n" + "=" * 80)
    print("File:", path)
    
    suffix = path.suffix.lower()
    
    try:
        if suffix == ".csv":
            df = pd.read_csv(path)
            print("Shape:", df.shape)
            display(df.head(n))
        
        elif suffix in [".xlsx", ".xls"]:
            df = pd.read_excel(path)
            print("Shape:", df.shape)
            display(df.head(n))
        
        elif suffix == ".json":
            with open(path, "r", encoding="utf-8") as f:
                obj = json.load(f)
            display(obj if isinstance(obj, dict) else obj[:n])
        
        elif suffix == ".npz":
            data = np.load(path, allow_pickle=True)
            print("Keys:", data.files)
            for key in data.files:
                arr = data[key]
                print(f"{key}: shape={arr.shape}, dtype={arr.dtype}")
                print(arr[:n] if arr.ndim > 0 else arr)
        
        else:
            print("Skipping unsupported type:", suffix)
    
    except Exception as e:
        print("Could not preview:", e)

supported_exts = {".csv", ".xlsx", ".xls", ".json", ".npz"}

for folder in [rawdata_dir, data_final_dir]:
    print("\n\n### Folder:", folder)
    files = [p for p in folder.rglob("*") if p.is_file() and p.suffix.lower() in supported_exts]
    print("Supported files found:", len(files))
    
    for p in files[:10]:
        preview_file(p)

### Folder: data/rawdata
Supported files found: 594

================================================================================
File: data/rawdata/WZ2/lap1/P7_S3_rainy_WZ2.csv
Shape: (86, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765395e+09,1,VEHICLE,287.4670,308.9990,0.0001,2.9156,12.3889,NaN,-0.076,0.393,0.0,NaN,NaN,False
1,0,1.765395e+09,2,PEDESTRIAN,231.2688,307.1827,1.6151,1.3942,NaN,NaN,NaN,NaN,NaN,-0.6016,-0.0105,False
2,1,1.765395e+09,1,VEHICLE,284.3798,309.5598,0.0001,2.9952,12.3056,-0.4167,-0.058,0.457,0.0,NaN,NaN,False
3,1,1.765395e+09,2,PEDESTRIAN,231.2580,307.1947,1.6220,1.2919,NaN,NaN,NaN,NaN,NaN,-0.5746,-0.0906,False
4,2,1.765395e+09,1,VEHICLE,282.9245,309.7471,-0.0000,3.0237,12.3056,0.0000,-0.040,0.469,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P21_S4_curve_WZ2.csv
Shape: (102, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772053e+09,1,VEHICLE,-106.6670,-151.8096,0.0526,0.0092,5.6111,NaN,-0.0,0.150,0.0,NaN,NaN,False
1,0,1.772053e+09,2,PEDESTRIAN,-55.5319,-140.1874,1.0372,2.5025,NaN,NaN,NaN,NaN,NaN,-0.6229,-0.0682,False
2,1,1.772053e+09,1,VEHICLE,-105.9576,-151.8030,0.0529,0.0093,4.9722,-3.1944,-0.0,0.246,0.0,NaN,NaN,False
3,1,1.772053e+09,2,PEDESTRIAN,-55.5300,-140.1670,1.0277,2.4923,NaN,NaN,NaN,NaN,NaN,-0.6521,-0.0473,False
4,2,1.772053e+09,1,VEHICLE,-104.9081,-151.7931,0.0521,0.0094,4.5278,-2.2222,-0.0,0.460,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P25_S3_rainy_WZ2.csv
Shape: (72, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772210e+09,1,VEHICLE,275.4479,310.2042,-0.0007,3.1037,9.4444,NaN,-0.012,0.541,0.0,NaN,NaN,False
1,0,1.772210e+09,2,PEDESTRIAN,229.5746,307.9645,1.0610,1.7324,NaN,NaN,NaN,NaN,NaN,-0.5974,-0.2014,False
2,1,1.772210e+09,1,VEHICLE,273.0291,310.2763,-0.0006,3.1141,9.7222,1.3889,-0.011,0.541,0.0,NaN,NaN,False
3,1,1.772210e+09,2,PEDESTRIAN,229.5728,307.9827,1.0098,1.6860,NaN,NaN,NaN,NaN,NaN,-0.6667,-0.2740,False
4,2,1.772210e+09,1,VEHICLE,270.9728,310.3181,-0.0007,3.1227,10.0000,1.3889,-0.011,0.541,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P22_S4_curve_WZ2.csv
Shape: (212, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772060e+09,1,VEHICLE,-150.3681,-151.3521,0.0503,-0.0355,2.6667,NaN,-0.008,0.528,0.0,NaN,NaN,False
1,0,1.772060e+09,2,PEDESTRIAN,-56.4942,-140.2833,1.5507,-3.0458,NaN,NaN,NaN,NaN,NaN,-0.7414,0.1072,False
2,1,1.772060e+09,1,VEHICLE,-150.0625,-151.3615,0.0503,-0.0345,2.8056,0.6944,-0.008,0.528,0.0,NaN,NaN,False
3,1,1.772060e+09,2,PEDESTRIAN,-56.4253,-140.2587,1.5735,-3.0489,NaN,NaN,NaN,NaN,NaN,-0.6473,0.0979,False
4,2,1.772060e+09,1,VEHICLE,-149.3257,-151.3831,0.0503,-0.0322,3.1389,1.6667,-0.007,0.528,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P18_S1_normal_WZ2.csv
Shape: (106, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.771526e+09,1,VEHICLE,184.0266,-107.3514,0.2153,2.9593,1.1944,NaN,-0.109,0.000,0.0,NaN,NaN,False
1,0,1.771526e+09,2,PEDESTRIAN,77.3820,-106.4271,1.9315,3.0732,NaN,NaN,NaN,NaN,NaN,-0.1145,-0.0112,False
2,1,1.771526e+09,1,VEHICLE,183.9023,-107.3333,0.2149,2.9621,1.0278,-0.8333,-0.012,0.488,0.0,NaN,NaN,False
3,1,1.771526e+09,2,PEDESTRIAN,77.4196,-106.4575,1.9286,3.0419,NaN,NaN,NaN,NaN,NaN,-0.1023,-0.0225,False
4,2,1.771526e+09,1,VEHICLE,183.6750,-107.2940,0.2142,2.9628,1.1111,0.4167,-0.021,0.750,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P5_S5_nighttime_WZ2.csv
Shape: (106, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765317e+09,1,VEHICLE,190.1466,-161.7096,0.2154,-1.5732,8.8611,NaN,0.001,0.400,0.0,NaN,NaN,False
1,0,1.765317e+09,2,PEDESTRIAN,189.3979,-219.4320,1.9815,1.5752,NaN,NaN,NaN,NaN,NaN,0.1796,-0.0382,False
2,1,1.765317e+09,1,VEHICLE,190.1403,-163.6732,0.2155,-1.5741,8.7778,-0.4167,0.001,0.451,0.0,NaN,NaN,False
3,1,1.765317e+09,2,PEDESTRIAN,189.4024,-219.4324,1.9862,1.6006,NaN,NaN,NaN,NaN,NaN,0.2201,-0.0639,False
4,2,1.765317e+09,1,VEHICLE,190.1328,-165.6303,0.2155,-1.5747,8.7778,0.0000,-0.001,0.469,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P17_S2_noWarning_WZ2.csv
Shape: (106, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.766001e+09,1,VEHICLE,-77.8135,-134.5256,-0.0063,-0.0875,7.9167,NaN,0.006,0.707,0.0,NaN,NaN,False
1,0,1.766001e+09,2,PEDESTRIAN,33.9981,-138.3908,1.0834,-1.7448,NaN,NaN,NaN,NaN,NaN,-1.0683,-0.1773,False
2,1,1.766001e+09,1,VEHICLE,-76.0510,-134.6867,-0.0060,-0.0913,8.5278,3.0556,0.007,0.711,0.0,NaN,NaN,False
3,1,1.766001e+09,2,PEDESTRIAN,34.0021,-138.4123,1.0219,-1.6444,NaN,NaN,NaN,NaN,NaN,-1.0758,-0.1246,False
4,2,1.766001e+09,1,VEHICLE,-73.9517,-134.8886,-0.0060,-0.0964,9.3889,4.3056,0.004,0.711,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P13_S4_curve_WZ2.csv
Shape: (116, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765824e+09,1,VEHICLE,-129.7235,-150.1391,0.0357,0.0123,4.5000,NaN,0.011,0.75,0.0,NaN,NaN,False
1,0,1.765824e+09,2,PEDESTRIAN,-56.0611,-140.3528,1.6980,-3.0959,NaN,NaN,NaN,NaN,NaN,0.1478,-0.1110,False
2,1,1.765824e+09,1,VEHICLE,-128.6161,-150.1323,0.0309,0.0077,5.3056,4.0278,0.010,0.75,0.0,NaN,NaN,False
3,1,1.765824e+09,2,PEDESTRIAN,-56.0133,-140.3905,1.7102,2.9788,NaN,NaN,NaN,NaN,NaN,0.0976,-0.0871,False
4,2,1.765824e+09,1,VEHICLE,-127.3097,-150.1314,0.0310,0.0025,5.3056,0.0000,0.010,0.75,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P21_S6_truck_WZ2.csv
Shape: (102, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772054e+09,1,VEHICLE,-62.7339,58.4700,-0.0049,-0.0009,12.3611,NaN,0.014,0.448,0.0,NaN,NaN,False
1,0,1.772054e+09,2,PEDESTRIAN,49.9725,57.3932,1.1324,1.0749,NaN,NaN,NaN,NaN,NaN,-0.0522,-0.0188,False
2,1,1.772054e+09,1,VEHICLE,-59.7679,58.4535,-0.0047,-0.0081,12.4167,0.2778,-0.012,0.443,0.0,NaN,NaN,False
3,1,1.772054e+09,2,PEDESTRIAN,49.9517,57.4109,1.1210,1.3507,NaN,NaN,NaN,NaN,NaN,-0.1395,-0.0211,False
4,2,1.772054e+09,1,VEHICLE,-58.1854,58.4515,-0.0047,-0.0014,12.4167,0.0000,-0.022,0.421,0.0,NaN,NaN,False

================================================================================
File: data/rawdata/WZ2/lap1/P8_S1_normal_WZ2.csv
Shape: (106, 16)

,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765483e+09,1,VEHICLE,177.1153,-109.2292,0.2135,3.0941,8.0278,NaN,-0.024,0.75,0.0,NaN,NaN,False
1,0,1.765483e+09,2,PEDESTRIAN,76.7684,-105.6211,1.3317,-1.8076,NaN,NaN,NaN,NaN,NaN,-1.1706,-0.6796,False
2,1,1.765483e+09,1,VEHICLE,175.2278,-109.1695,0.2137,3.1107,8.8611,4.1667,-0.024,0.75,0.0,NaN,NaN,False
3,1,1.765483e+09,2,PEDESTRIAN,76.7619,-105.6174,1.3658,-1.8153,NaN,NaN,NaN,NaN,NaN,-1.1455,-0.6631,False
4,2,1.765483e+09,1,VEHICLE,174.2360,-109.1501,0.2137,3.1195,9.3056,2.2222,-0.025,0.75,0.0,NaN,NaN,False

### Folder: data/data_final
Supported files found: 1

================================================================================
File: data/data_final/sample_manifest.csv
Shape: (13905, 7)

,file,scene_id,sample_idx,participant,scenario,wz,t_anchor
0,P10_S1_normal_WZ1_s0000.pkl,P10_S1_normal_WZ1,0,P10,S1_normal,1,1.765554e+09
1,P10_S1_normal_WZ1_s0001.pkl,P10_S1_normal_WZ1,1,P10,S1_normal,1,1.765554e+09
2,P10_S1_normal_WZ1_s0002.pkl,P10_S1_normal_WZ1,2,P10,S1_normal,1,1.765554e+09
3,P10_S1_normal_WZ1_s0003.pkl,P10_S1_normal_WZ1,3,P10,S1_normal,1,1.765554e+09
4,P10_S1_normal_WZ1_s0004.pkl,P10_S1_normal_WZ1,4,P10,S1_normal,1,1.765554e+09

In [14]:
from pathlib import Path
import pickle

DATA_DIR = Path("data")
pkl_files = list((DATA_DIR / "data_final").rglob("*.pkl"))

print("num pkl files:", len(pkl_files))
print("first pkl:", pkl_files[0])

with open(pkl_files[0], "rb") as f:
    sample = pickle.load(f)

print(type(sample))

if isinstance(sample, dict):
    print("keys:", sample.keys())
    for k, v in sample.items():
        print("\nKEY:", k)
        print("TYPE:", type(v))
        try:
            print("SHAPE:", v.shape)
        except:
            pass
        print("VALUE PREVIEW:", str(v)[:500])
else:
    print(sample)

num pkl files: 13905
first pkl: data/data_final/WZ2/lap1/P27_S2_noWarning_WZ2_s0003.pkl
<class 'dict'>
keys: dict_keys(['meta', 'ego_ref', 'agents', 'map'])

KEY: meta
TYPE: <class 'dict'>
VALUE PREVIEW: {'scene_id': 'P27_S2_noWarning_WZ2', 'sample_idx': 3, 't_anchor': 1772492700.929, 'participant': 'P27', 'scenario': 'S2_noWarning', 'wz': 2}

KEY: ego_ref
TYPE: <class 'dict'>
VALUE PREVIEW: {'pos_world': [-6.6113, -140.0374], 'heading_world': -0.0351}

KEY: agents
TYPE: <class 'dict'>
VALUE PREVIEW: {'ids': [1, 2, 'sumo_car_4'], 'types': ['VEHICLE', 'PEDESTRIAN', 'VEHICLE'], 'extents': array([[4.93, 1.91, 1.48],
       [0.5 , 0.5 , 1.8 ],
       [4.79, 1.85, 1.45]], dtype=float32), 'obs_xy': array([[[-2.5125530e+01, -8.2483310e-01],
        [ 3.9383110e+01,  3.3838475e+00],
        [ 2.2088141e+00, -5.2656996e-01]],

       [[-2.1122950e+01, -5.8592415e-01],
        [ 3.9305172e+01,  3.3693035e+00],
        [ 4.9660673e+00, -4.6825698e-01]],

       [[-1.7661251e+01, -4.1113585e-01],


KEY: map
TYPE: <class 'dict'>
VALUE PREVIEW: {'wz_cones': None, 'wz_corners': [[37.45873246413129, 5.00501434869442], [46.05343536500472, 5.306812370089356], [46.16222302387963, 2.208721789541964], [37.567520123006204, 1.9069237681470277]], 'wz_warning': None, 'wz_workers': None, 'lanes': [{'uid': '1.0.-2', 'polyline': [[25.958331889617803, -0.01157191631748311, 0.04069288067843768], [26.45811428569886, 0.0031835740701873227, 0.04069288067843768], [26.957897217253446, 0.017923815067320548, 0.04069288067843768], [27.457679613334502, 0.03267

In [15]:
from pathlib import Path
import pickle
import numpy as np

pkl_files = list(Path("data/data_final").rglob("*.pkl"))
p = pkl_files[0]

with open(p, "rb") as f:
    sample = pickle.load(f)

print("FILE:", p)

print("\nMETA:")
print(sample["meta"])

print("\nEGO_REF:")
print(sample["ego_ref"])

print("\nAGENTS KEYS:")
for k, v in sample["agents"].items():
    print("\nKEY:", k)
    print("TYPE:", type(v))
    if hasattr(v, "shape"):
        print("SHAPE:", v.shape)
        print("DTYPE:", v.dtype)
        print("PREVIEW:", v[:2] if v.ndim > 0 else v)
    else:
        print("VALUE:", v)

print("\nMAP KEYS:")
for k, v in sample["map"].items():
    print("\nKEY:", k)
    print("TYPE:", type(v))
    if hasattr(v, "shape"):
        print("SHAPE:", v.shape)
        print("DTYPE:", v.dtype)
    elif isinstance(v, list):
        print("LEN:", len(v))
        print("PREVIEW:", str(v[:2])[:800])
    else:
        print("VALUE:", str(v)[:800])

FILE: data/data_final/WZ2/lap1/P27_S2_noWarning_WZ2_s0003.pkl

META:
{'scene_id': 'P27_S2_noWarning_WZ2', 'sample_idx': 3, 't_anchor': 1772492700.929, 'participant': 'P27', 'scenario': 'S2_noWarning', 'wz': 2}

EGO_REF:
{'pos_world': [-6.6113, -140.0374], 'heading_world': -0.0351}

AGENTS KEYS:

KEY: ids
TYPE: <class 'list'>
VALUE: [1, 2, 'sumo_car_4']

KEY: types
TYPE: <class 'list'>
VALUE: ['VEHICLE', 'PEDESTRIAN', 'VEHICLE']

KEY: extents
TYPE: <class 'numpy.ndarray'>
SHAPE: (3, 3)
DTYPE: float32
PREVIEW: [[4.93 1.91 1.48]
 [0.5  0.5  1.8 ]]

KEY: obs_xy
TYPE: <class 'numpy.ndarray'>
SHAPE: (10, 3, 2)
DTYPE: float32
PREVIEW: [[[-25.12553     -0.8248331 ]
  [ 39.38311      3.3838475 ]
  [  2.2088141   -0.52656996]]

 [[-21.12295     -0.58592415]
  [ 39.305172     3.3693035 ]
  [  4.9660673   -0.46825698]]]

KEY: obs_heading
TYPE: <class 'numpy.ndarray'>
SHAPE: (10, 3)
DTYPE: float32
PREVIEW: [[ 0.0629     -2.2481      0.01136351]
 [ 0.0543     -2.2558      0.01991558]]

KEY: obs_speed
TYPE: <class 'numpy.ndarray'>
SHAPE: (10, 3)
DTYPE: float32
PREVIEW: [[16.2778     nan 14.276 ]
 [15.6389     nan 14.302 ]]

KEY: obs_mask
TYPE: <class 'numpy.ndarray'>
SHAPE: (10, 3)
DTYPE: bool
PREVIEW: [[ True  True  True]
 [ True  True  True]]

KEY: fut_xy
TYPE: <class 'numpy.ndarray'>
SHAPE: (25, 3, 2)
DTYPE: float32
PREVIEW: [[[ 2.39567351e+00 -1.13361105e-02]
  [ 3.90895500e+01  3.60268044e+00]
  [            nan             nan]]

 [[ 3.58191919e+00 -2.60164738e-02]
  [ 3.91004219e+01  3.58935380e+00]
  [            nan             nan]]]

KEY: fut_mask
TYPE: <class 'numpy.ndarray'>
SHAPE: (25, 3)
DTYPE: bool
PREVIEW: [[ True  True False]
 [ True  True False]]

MAP KEYS:

KEY: wz_cones
TYPE: <class 'NoneType'>
VALUE: None

KEY: wz_corners
TYPE: <class 'list'>
LEN: 4
PREVIEW: [[37.45873246413129, 5.00501434869442], [46.05343536500472, 5.306812370089356]]

KEY: wz_warning
TYPE: <class 'NoneType'>
VALUE: None

KEY: wz_workers
TYPE: <class 'NoneType'>
VALUE: None

KEY: lanes
TYPE: <class 'list'>
LEN: 23
PREVIEW: [{'uid': '1.0.-2', 'polyline': [[25.958331889617803, -0.01157191631748311, 0.04069288067843768], [26.45811428569886, 0.0031835740701873227, 0.04069288067843768], [26.957897217253446, 0.017923815067320548, 0.04069288067843768], [27.457679613334502, 0.03267930545499087, 0.04069288067843768], [27.957462009415554, 0.047434795842661304, 0.04069288067843768], [28.457242499322795, 0.06219021929614055, 0.04069288067843768], [28.95702543087738, 0.076930460293274, 0.04069288067843768], [29.456807826958435, 0.0916859506809441, 0.04069288067843768], [29.95659022303949, 0.10644144106861442, 0.04069288067843768], [30.456372619120543, 0.12119693145628474, 0.04069288067843768], [30.95615555067513, 0.1359371724534182, 0.04069288067843768], [31.455937946756183, 0.1506926628410885, 0.04069288067843768], [31.